# Input/Output

```{r iosetup, include=FALSE, eval=TRUE, cache=FALSE}
knitr::opts_chunk$set(echo = T, message=F, warning=F, comment=NA, autodep=T, eval=FALSE, cache.rebuild=F, cache=F,
                      R.options=list(width=120), fig.width=8, fig.align = 'center')
```


Standard methods of reading in data include the following functions:

- <span class="func">read.table</span>
- <span class="func">read.csv</span>
- <span class="func">readLines</span>

Base R also comes with the <span class="pack">foreign</span> package for reading in other types of files, especially other statistical packages. However, while you may see it still in use, it's not as useful as what's found in other packages.


### Newer approaches

<span class="pack">haven</span>: Package to read in foreign statistical files

  - <span class="func">read_spss</span>
  - <span class="func">read_dta</span>

<span class="pack">readxl</span>: for excel files

<span class="pack">rio</span>: uses haven, readxl etc. but with just two functions for everything

- <span class="func">import</span>, <span class="func">export</span> (also <span class="func">convert</span>)


### Faster approaches

<span class="pack">readr</span>: Faster versions of base R functions

  - <span class="func">read_csv</span>
  - <span class="func">read_delim</span>

These make assumptions after an initial scan of the data, but if you don't have 'big' data, this won't help much.

However, they actually can be used as a diagnostic.

  - pick up potential data entry errors.


<span class="pack">data.table</span> provides a faster version <span class="func">read.table</span>, and is typically faster than <span class="pack">readr</span> approaches.

  - <span class="func">fread</span>




### Other Data

Note that R can handle many types of data.

Some examples:

- JSON
- SQL
- XML
- YAML
- MongoDB
- NETCDF
- text (e.g. a novel)
- shapefiles
- google spreadsheets

And many, many others.


### On the horizon
 
<span class="pack">feather</span>: designed to make reading/writing data frames efficient

Works in both Python and R. Still in early stages of development.


### Exercises

#### Thinking Exercises

Why might you use <span class="func">read_csv</span> from the <span class="pack">readr</span> package rather than <span class="func">read.csv</span> in base R?

What is your definition of 'big' data?