# Indexing

```{r setupidx, include=FALSE, eval=TRUE}
knitr::opts_chunk$set(echo = T, message=F, warning=F, comment=NA, autodep=T, eval=FALSE, cache.rebuild=F, cache=F,
                      R.options=list(width=120), fig.width=8, fig.align = 'center')
```


### Base R Indexing Refresher

##### Slicing vectors

```{r vectorSlice, eval=TRUE}
letters[4:6]
letters[c(13,10,3)]
```

##### Slicing matrices/data.frames

```{r matrixSlice}
myMatrix[1, 2:3]
```


##### Label-based indexing

```{r dfindexlabel}
mydf['row1', 'b']
```

##### Position-based indexing

```{r dfindexpos}
mydf[1, 2]
```


##### Mixed indexing

```{r dfindexmix}
mydf['row1', 2]
```

If the row/column value is empty, all rows/columns are retained.

```{r dfindexslice}
mydf['row1',]
mydf[,'b']
```


##### Non-contiguous

```{r dfindexnoncont}
mydf[c(1,3),]
```

##### Boolean

```{r dfindexbool}
mydf[mydf$a >= 2,]
```


### List/Data.frame extraction

<span class="func">[</span> : grab a slice of elements/columns

<span class="func">[[</span> : grab specific elements/columns

<span class="func">$</span> : grab specific elements/columns

<span class="func">@</span>: extract slot for S4 objects

```{r dflistslice}
my_list_or_df[2:4]
```


```{r dflistextract}
my_list_or_df[['name']]
```

```{r dflistextract2}
my_list_or_df$name
```
