# Intro

This document is the basis for multiple workshops, whose commmon goal is to provide some tools, tips, packages etc. that make data processing and visualization in R easier.  It is oriented toward those who have had some exposure to R in an applied fashion, but would also be useful to someone coming to R from another programming language.  It is *not* an introduction to R, nor does this document have anything to do with statistical analysis (yet).  The goal here is primarily to instill awareness, specifically of tools that will make your data exploration easier, and to understand some of the *why* behind the tools, so that one can better implement them.


## Outline

### Part 1: Data Processing

#### Understanding Base R Approaches to Data Processing

- Overview of Data Structures
- Input/Output
- Vectorization and Apply functions

####  Getting Acquainted with Other Approaches to Data Processing

- Pipes, and how to use them
- tidyverse
- data.table
- Misc.

### Part 2: Visualization

#### Thinking Visually

- Visualizing Information
- Color
- Contrast
- and more...

#### ggplot2

- Aesthetics
- Layers
- Themes
- and more...

#### Adding Interactivity

- Package demos
- Shiny


Future... ?

### Part 3: Programming Basics

### Part 4: Presentation

### Part 5: Modeling



## Preparation

To follow along with some of the examples in the data processing section, create a new RStudio project (File/New Project/New Directory/New Project/...). After that, download the data zip file and unzip the contents to your project folder.  You will then have easy access to much of the data used in the examples (that isn't already accessible via packages, base R, etc.). Some are `.RData` files, while others might be raw `.csv`.

[Zipped Data File](https://github.com/m-clark/data-processing-and-visualization/blob/master/data.7z?raw=true)


## Other

Color coding in text:

- <span class="emph">emphasis</span>
- <span class="pack">package</span>
- <span class="func">function</span>
- <span class="objclass">object/class</span>
- [link]()

Some key packages used in the following demonstrations and exercises:

tidyverse (several packages), data.table, ggplot2movies 


Many others are also used, feel free to install as we come across them. Here are a few.

DT, highcharter, magrittr, maps, mgcv (already comes with base R), plotly, quantmod, readr, visNetwork
