---
---

## 

<div style="text-align:center; font-size:200%; font-variant:small-caps;" ><span style='color:#1e90ff'>Input/Output</span></div>


## Input/Output

Standard methods of reading in data

  - <span class="func">read.table</span>
  - <span class="func">read.csv</span>
  - <span class="func">readLines</span>

Using the <span class="pack">foreign</span> package:

  - <span class="func">read.spss</span>
  - <span class="func">read.xport</span>

Note: the foreign package is no longer useful for Stata files.


## Newer approaches

<span class="pack">haven</span>: Package to read in foreign statistical files

  - <span class="func">read_spss</span>
  - <span class="func">read_dta</span>

<span class="pack">readxl</span>: for excel files



## Faster approaches

<span class="pack">readr</span>: Faster versions of base R functions

  - <span class="func">read_csv</span>
  - <span class="func">read_delim</span>

These make assumptions after an initial scan of the data.

If you don't have 'big' data, this won't help much.

However, they actually can be used as a diagnostic.

  - pick up potential data entry errors.



## Faster approaches

<span class="pack">data.table</span>: faster read.table

  - <span class="func">fread</span>

Typically faster than <span class="pack">readr</span> approaches.


## Other Data

Note that R can handle many types of data.

Some examples:

- JSON
- SQL
- XML
- YAML
- MongoDB
- NETCDF
- text (e.g. a novel)
- shapefiles
- google spreadsheets

And many, many others.


## On the horizon
 
<span class="pack">feather</span>: designed to make reading/writing data frames efficient

Works in both Python and R.

Still in early stages of development.